### ISSUE TITLE
ffmpeg takes over stdin

### ISSUE THREAD

**Issue by wtanksleyjr** [ping/odmpy#13]
The ffmpeg command sometimes reads from stdin even when it isn't asked to. The result is that odmpy will appear to produce strange output about failure to parse debug commands (and it's entirely possible that in some cases stdin will contain some valid debug command that could really mess things up).

In my case, I called odmpy from inside a bash while loop on "ls *.odm | while read line ...", and because ffmpeg was eating stdin, the while loop would only process the first successful file.

This can be resolved by always running ffmpeg with the `-nostdin` option, or by always running with redirection from /dev/null.

See also https://superuser.com/questions/1492507/why-does-ffmpeg-require-nostdin-in-while-loop

**Comment by ping** [comment]
Thanks, I have added the ``-nostdin`` option.
