### ISSUE TITLE
FILE_PART_RE does not always match second_stamp

### ISSUE THREAD

**Issue by lullius** [ping/odmpy#28]
```python
FILE_PART_RE = re.compile(
    r"(?P<part_name>{[A-F0-9\-]{36}}[^#]+)(#(?P<second_stamp>\d+))?$"
)
```
I recently received an [issue](https://github.com/lullius/pylibby/issues/25) on my repository which uses the same regex. The regex will not match with this:

```json
"path": "{31984D68-AD8F-4EF1-B00C-4A595BADE0D1}Fmt425-Part01.mp3#275.253"
```

The timestamp does not appear to be an integer (275.253) and will make odmpy crash when using libby with --direct. The book in question is the book with id [114614](https://www.overdrive.com/media/114614/the-tiger-in-the-well). Downloading works fine without --direct.

**Comment by ping** [comment]
Thanks for passing on the issue. Fixed in 7c116b8ac5519545c0aafc1696c8dc6af7819fb7.
