### ISSUE TITLE
Crash when title contains a /  ( forward slash ) on win11 in version 0.6.7

### ISSUE THREAD

**Issue by jvandervort** [ping/odmpy#30]
Crash when title contains a /  ( forward slash ) on win11 in version 0.6.7
I was able to get past this by downloading the odm and changing the / to a - and re-running.

**Comment by ping** [comment]
Can you provide the exact command used, and the full crash trace messages?

**Comment by jvandervort** [comment]
Will do, I'll need to check it out again so it might be a little while.

**Comment by ping** [comment]
Which command did you actually use to download? `odmpy dl` or `odmpy libby` and what options did you use?

Unless you have returned the loan, you can just repeat what you did before (after moving your existing downloaded files to a backup location).

If you used the `odmpy dl` command, you will have to download a fresh copy of the `odm` file to try.
If you used the `odmpy libby` command, there should be nothing to else to do except to just run the command again.

I've specifically tested for this situation with Stephen King's 11/22/63 and it does work for me. But I've not tested on Windows so there may be some Windows-specific issues.

**Comment by jvandervort** [comment]
It created a folder with only the text preceding the /

The following reserved windows characters:
* < (less than)
* \> (greater than)
* : (colon)
* " (double quote)
* / (forward slash)
* \ (backslash)
* | (vertical bar or pipe)
* ? (question mark)
*  \* (asterisk)


```
C:\Users\nnn\Downloads>python -m odmpy libby
Libby Interactive Client
----------------------------------------------------------------------
Found 1 downloadable loans.
 1: The Complete Earthsea Series / The Left Hand of Darkness  By: Ursula.K.Le Guin
    * Expires: 2023-03-05  

Choose from 1-1 (separate choices with a space or leave blank to quit),
then press enter: 1
Opening book "The Complete Earthsea Series / The Left Hand of Darkness"...
Downloaded odm to .\the-complete-earthsea-series-the-left-hand-of-darkness-6517000.odm
Downloading "The Complete Earthsea Series / The Left Hand of Darkness" by "Ursula.K.Le Guin" in 9 part(s)...
An unexpected error has occured
Traceback (most recent call last):
  File "C:\Users\nnn\AppData\Roaming\Python\Python311\site-packages\odmpy\odm.py", line 589, in run
    process_odm(
  File "C:\Users\nnn\AppData\Roaming\Python\Python311\site-packages\odmpy\processing.py", line 270, in process_odm
    book_folder, book_filename, book_m4b_filename = generate_names(
                                                    ^^^^^^^^^^^^^^^
  File "C:\Users\nnn\AppData\Roaming\Python\Python311\site-packages\odmpy\shared.py", line 77, in generate_names
    os.makedirs(book_folder)
  File "<frozen os>", line 225, in makedirs
FileNotFoundError: [WinError 3] The system cannot find the path specified: '.\\The Complete Earthsea Series / The Left Hand of Darkness - Ursula.K.Le Guin'
```

**Comment by ping** [comment]
@jvandervort Thanks for the details. It was very useful to identify the problem.

I've put in a fix on the `master` branch. Can you update your copy and give it a test?

**Comment by jvandervort** [comment]
Works great! Thanks
