### ISSUE TITLE
Window/unix difference with os.rename

### ISSUE THREAD

**Issue by jvandervort** [ping/odmpy#31]
To get the tests to pass I had to update os.rename to os.replace

shared.py
![image](https://user-images.githubusercontent.com/472951/218487697-b54572b2-407b-493d-8740-a99e73fbe6f7.png)

Pretty crazy difference between Windows and Unix behavior
> On Windows, if dst exists a [FileExistsError](https://docs.python.org/3/library/exceptions.html#FileExistsError) is always raised. The operation may fail if src and dst are on different filesystems. Use [shutil.move()](https://docs.python.org/3/library/shutil.html#shutil.move) to support moves to a different filesystem.

> On Unix, if src is a file and dst is a directory or vice-versa, an [IsADirectoryError](https://docs.python.org/3/library/exceptions.html#IsADirectoryError) or a [NotADirectoryError](https://docs.python.org/3/library/exceptions.html#NotADirectoryError) will be raised respectively. If both are directories and dst is empty, dst will be silently replaced. If dst is a non-empty directory, an [OSError](https://docs.python.org/3/library/exceptions.html#OSError) is raised. If both are files, dst will be replaced silently if the user has permission. The operation may fail on some Unix flavors if src and dst are on different filesystems. If successful, the renaming will be an atomic operation (this is a POSIX requirement).

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\nnn\Documents\dev\git\odmpy\odmpy\__main__.py", line 32, in <module>
    main()
  File "C:\Users\nnn\Documents\dev\git\odmpy\odmpy\__main__.py", line 26, in main
    run()
  File "C:\Users\nnn\Documents\dev\git\odmpy\odmpy\odm.py", line 764, in run
    process_odm(args.odm_file, args, logger)
  File "C:\Users\nnn\Documents\dev\git\odmpy\odmpy\processing.py", line 590, in process_odm
    merge_into_mp3(
  File "C:\Users\nnn\Documents\dev\git\odmpy\odmpy\shared.py", line 322, in merge_into_mp3
    os.rename(temp_book_filename, book_filename)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'tests/data/downloads/Ceremonies For Christmas - Robert Herrick\\Ceremonies For Christmas - Robert Herrick.mp3.part' -> 'tests/data/downloads/Ceremonies For Christmas - Robert Herrick\\Ceremonies For Christmas - Robert Herrick.mp3'
```

**Comment by ping** [comment]
Were you able to execute [`run_tests.sh`](https://github.com/ping/odmpy/blob/master/run_tests.sh) on Windows?

The rename seems to have failed because ''tests/data/downloads/Ceremonies For Christmas - Robert Herrick\\Ceremonies For Christmas - Robert Herrick.mp3'' already exists. I'm guessing this was remnant output from a previous test that was not properly cleared.

**Comment by ping** [comment]
Switching over to `os.replace()` seems a fairly minor change so I've gone ahead and done that on the `master` branch.

**Comment by jvandervort** [comment]
Yes, I ran the tests using git bash on windows, the tests with a basic charset usage pass fine, but the full UTF-8 tests fail.  On windows the default charset is cp1252 it is dies on the extended characters, and I can't figure out where the windows 'default' encoding is applied when running the tests.

And yes, exactly that -above-.  The remnant of the previous merge test causes the second one to fail on windows.

```
# download + merge into mp3
  rm -rf "$TEST_DOWNLOAD_DIR" && mkdir -p "$TEST_DOWNLOAD_DIR"
  python -m odmpy dl "$TEST_DATA_DIR/$TEST_ODM" -d "$TEST_DOWNLOAD_DIR" -m --hideprogress > /dev/null
  python -m unittest -v tests.OdmpyTests.test_download_2
  # download + merge into m4b
  python -m odmpy dl "$TEST_DATA_DIR/$TEST_ODM" -d "$TEST_DOWNLOAD_DIR" -m --mergeformat m4b --hideprogress > /dev/null
  python -m unittest -v tests.OdmpyTests.test_download_3
```

**Comment by jvandervort** [comment]
not sure what your supported python versions are, but os.replace is 3.3+
you could delete if exists before os.rename if you wanted to keep it.

**Comment by ping** [comment]
> not sure what your supported python versions are, but os.replace is 3.3+ you could delete if exists before os.rename if you wanted to keep it.

Python support is >=3.7 so I think it should be fine. Thanks for the report.
