### ISSUE TITLE
Missing CoverUrl in ODM causes crash

### ISSUE THREAD

**Issue by wtanksleyjr** [ping/odmpy#4]
Some ODMs do not include a link to a cover image (they show up in the Overdrive application with a question mark image in place of the cover image). In ODMs of this sort, odmpy will crash due to a conditional that seems to test the possibility of a missing image, but which actually doesn't have any alternate behavior.

The one-line conditional shown below dereferences the pointer whether or not it's null.
```
Traceback (most recent call last):
  File "/home/william/.local/bin/odmpy", line 8, in <module>
    sys.exit(main())
  File "/home/william/.local/lib/python3.6/site-packages/odmpy/__main__.py", line 26, in main
    run()
  File "/home/william/.local/lib/python3.6/site-packages/odmpy/odm.py", line 216, in run
    cover_url = metadata.find('CoverUrl').text if metadata.find('CoverUrl') else metadata.find('CoverUrl').text
AttributeError: 'NoneType' object has no attribute 'text'
```

**Comment by ping** [comment]
This should be fixed in master. Please report back if it's not working for you.
