### ISSUE TITLE
would love an option to just download new books

### ISSUE THREAD

**Issue by jahlborn** [ping/odmpy#42]
**Describe the problem**
I'd like to be able to run this program in a background job to periodically check for new books and automatically download them.  the `--latest N` command sort of does that because it will recognize already downloaded books and not redownload them.  however it would be great if there was a command like `--new` which compares all the available books with what exists locally and then downloads any books that were not currently downloaded.

**Comment by wtanksleyjr** [comment]
I was building a script to do this (but got distracted). However, I didn't know that `--latest N` would check before downloading -- how does it perform the check? Wouldn't just using --latest with a big number solve the problem?

With that said, my plan to implement this (before I got distracted) was to use `odmpy --exportloans loans.json`, then get the individual book IDs (something like `cat loans.json | jq '.[].id'`, but I haven't tested that) then remove the IDs I've already processed, and then call `odmpy --selectid [list of IDs]`.

**Comment by wtanksleyjr** [comment]
OK, this works to filter and show only the loans I've downloaded: `cat loans.json | jq '.[].id' | sort -u | sed 's/"//g' | combine - not <(cd ~/au/sources/libby/ && ls)`
(That's `combine` from `moreutils`, and obviously this is after `odmpy --exportloans loans.json`).
Then you can pass that almost directly to `odmpy --selectid` ... the only hard part is figuring out how I need to set up the download directory, as well as how to best get the metadata.

**Comment by wtanksleyjr** [comment]
One comment: there used to be another project on `github` that automatically downloaded all my checked-out libby books. It's gone now, the whole project's missing. The two facts might be related, although I don't know for sure.

**Comment by ping** [comment]
Like what was mentioned, using `--latest N` with a sufficiently large number should work for you unless you move the previously downloaded files to a different location.

What is it about `--latest` that is an issue for your use case?

**Comment by jahlborn** [comment]
> Like what was mentioned, using `--latest N` with a sufficiently large number should work for you unless you move the previously downloaded files to a different location.
> 
> What is it about `--latest` that is an issue for your use case?

yeah, latest with a large number would probably work.  i thought it might be cleaner to have an option which specifically was targeted at getting all new books, but i can make latest work.

**Comment by jahlborn** [comment]
@ping another issue that i noticed just now as i was testing this out is that even though `--latest` doesn't re-download the files, it does modify the files, so when i check for newly modified files, the stuff that has already been downloaded shows up as "new" again.  so maybe i don't need `--new`, but would it be possible to make it so that `--latest` doesn't modify existing files?

**Comment by ping** [comment]
> @ping another issue that i noticed just now as i was testing this out is that even though `--latest` doesn't re-download the files, it does modify the files, so when i check for newly modified files, the stuff that has already been downloaded shows up as "new" again. so maybe i don't need `--new`, but would it be possible to make it so that `--latest` doesn't modify existing files?

Existing audiofile downloads will no longer have their ID3 updated in affc94c5e576fd0b6df29222ee8b614ec177dfb7
You can test this by installing from the latest source.

**Comment by jahlborn** [comment]
> > @ping another issue that i noticed just now as i was testing this out is that even though `--latest` doesn't re-download the files, it does modify the files, so when i check for newly modified files, the stuff that has already been downloaded shows up as "new" again. so maybe i don't need `--new`, but would it be possible to make it so that `--latest` doesn't modify existing files?
> 
> Existing audiofile downloads will no longer have their ID3 updated in [affc94c](https://github.com/ping/odmpy/commit/affc94c5e576fd0b6df29222ee8b614ec177dfb7) You can test this by installing from the latest source.

hmmm, did an upgrade, force-reinstall of the latest and saw the same behavior (local modification times changed).

**Comment by ping** [comment]
Can you provide the actual command you are using?

Also, are you looking at the modification time of the folder or the actual mp3 files?

**Comment by jahlborn** [comment]
> Can you provide the actual command you are using?
> 
> Also, are you looking at the modification time of the folder or the actual mp3 files?

command:
`odmpy libby --latest 10 --hideprogress --downloaddir AudioBooks`

i'm looking at the modification times of the mp3 files.  (running this all on ubuntu linux box).

**Comment by ping** [comment]
My bad. I missed out on the changes for odm-based downloads. Can you update from source and try again?

**Comment by jahlborn** [comment]
> My bad. I missed out on the changes for odm-based downloads. Can you update from source and try again?

yep, that did it, thanks!  guess i'll call this good to go.  thanks again for an awesome utility.
