### ISSUE TITLE
Feature: Only download ebooks/magazines option

### ISSUE THREAD

**Issue by nfg42** [ping/odmpy#43]
Can you add an --audiobooks switch or maybe --noaudio to just download ebooks/magazines? Thanks.

**Comment by ping** [comment]
odmpy began as an audiobook-only tool, so audiobooks will always be default. This is to avoid breaking the tool for existing users.

`--noaudiobooks` will now exclude audiobooks, and is available if you update from master.

**Comment by nfg42** [comment]
Thanks, that's exactly what I was thinking.
