### ISSUE TITLE
Suggestion - Add %(ReadingOrder) to the --bookfolderformat options

### ISSUE THREAD

**Issue by snarfsmojo** [ping/odmpy#44]
I am using AudioBookShelf to host audiobooks.  it wants books that are series to be stored in the following folder format

.\%AuthorName%\%SeriesName%\Book %ReadingOrder% - %Title%\ 

having the ability to specify the ReadingOrder in the --bookfolderformat would be SUPER helpful!

Thanks much!

Snarf

**Comment by ping** [comment]
Thanks for the suggestion.

You can now use `%(ReadingOrder)s` in format strings for `--bookfolderformat`/`--bookfileformat` if you update from master or with the next release.

**Comment by ping** [comment]
This is now available from the [0.7.9](https://github.com/ping/odmpy/releases/tag/0.7.9) release.
