### ISSUE TITLE
new problem with version update

### ISSUE THREAD

**Issue by frankelrs** [ping/odmpy#46]
it seems that pip3 no longer works after install of pipx
uninstalling pipx doesnt help, also my python version is 3.11, some writers on the internet claim that pipx is required 
for new ubuntu

should i give up on odmpy for a while?  is there an another way to add missing python libraries?
sorry to bother you, im really impressed by your work. but this old hardware engineer can't seem to work problems of this complexity,
to be really clear its not your script its some python3 pip  pipx changes.
thank you for any suggestions

bob

.  
A clear and concise description of what the bug/error is. If there is an error traceback dump, paste the text here (please avoid screenshots).

**To Reproduce**
Please include the full command used, for example `odmpy libby --direct`

**Version/Environment**
Please paste the contents of `odmpy --version` here.

**Comment by ping** [comment]
I do not use pipx myself but it would be extremely odd if pipx breaks pip since it depends on pip.

What command are you using to install/upgrade? And what are the exact error messages?

**Comment by ping** [comment]
Closing due to a lack of response.
