### ISSUE TITLE
[Suggestion] allow inserting Libby IDs in book folder format

### ISSUE THREAD

**Issue by wtanksleyjr** [ping/odmpy#47]
When using Libby IDs to download, and perhaps when using Libby in general, it would be nice to be able to insert the Libby ID into the book folder. Right now it appears that %(id) inserts the ODM ID instead, which is inconvenient when batch-downloading by Libby ID (since my script doesn't know the ODM ID in advance, it can't tell where the resulting folder will be created).

Workaround: the ODM ID looks like it's in the --exportloans file, so if that turns out to be true I can complexify my script to convert between the two. I'll see what I can figure out.

**Comment by ping** [comment]
Thanks for the suggestion. `%(ID)s` now inserts the loan title ID instead of the reserve ID (when using `odmpy libby`).

You can try this by updating from master or wait the next release.

**Comment by ping** [comment]
Closing because this is now available from the latest v0.8.0 release.
