### ISSUE TITLE
option for escaping characters in folder/file names

### ISSUE THREAD

**Issue by jahlborn** [ping/odmpy#48]
**Describe the problem**
I've found that folder/file names which contain a ':' character cause issues on some filesystems.  I wonder if it would be possible to provide a mechanism to escape/replace/remove that character (or certain characters) for folder/file names.

**To Reproduce**
Download an audio book with a ':' in the title.

**Version/Environment**
odmpy 0.7.7 [Python 3.8.10-linux]

**Comment by ping** [comment]
Do you have an error stack trace for the problem?

**Comment by jahlborn** [comment]
The odmpy program doesn't generate an error. But, for example, I save the audiobooks to a drive which is shared via samba. When I view the shared directory for one of these problem books from another device, I don't see the normal folder name, instead I see some alternate name like "S488D~F", which I believe is some way of handling shared file names with illegal characters.

**Comment by ping** [comment]
You can now specify characters to remove from path/file names with `--removefrompaths`.

Example:
```bash
odmpy libby --removefrompaths ":,"
```
will replace colons and commas in file/path names with "-".

This is available if you update from master or with the next release.

**Comment by jahlborn** [comment]
awesome, thanks!

**Comment by ping** [comment]
Closing because this is now available from the latest v0.8.0 release.
