### ISSUE TITLE
Feature: Download books that can only be read with the Libby app

### ISSUE THREAD

**Issue by SamPixelYork** [ping/odmpy#50]
Some books can only be opened with the Libby app (similar to magazines), would be awesome to have a way of downloading these.

**Comment by ping** [comment]
Do you have examples?

**Comment by SamPixelYork** [comment]
[Tomb Raider: The Beginning by Rhianna Pratchett](https://libbyapp.com/search/sno-isle/search/query-tomb%20raider/page-1/2359656) is one example, generally I find it is graphic novels/comics that are only available to be read in the Libby app

**Comment by ping** [comment]
Those would probably extract as fixed-layout epubs. There are also fixed-layout magazines (mainly heavy image-spread type magazines like fashion ones) that odmpy does **not** support as well.

I only intend to support text-based publications for now. Reader software for these types of fixed-layout books are also fairly limited afaik.
