### ISSUE TITLE
Is the latest version of this project 0.8.0 or 0.80?

### ISSUE THREAD

**Issue by jfly** [ping/odmpy#52]
On https://github.com/ping/odmpy/releases/tag/0.8.0, I see a release titled "Release 0.80", but the git tag is [0.8.0](https://github.com/ping/odmpy/tree/0.8.0), which makes me think it's really just a typo in the release name.

**Comment by ping** [comment]
Thanks for the report. It's a typo, now fixed.

**Comment by jfly** [comment]
Thank you!
