### ISSUE TITLE
How can i use it? I do not know python.

### ISSUE THREAD

**Issue by ojmw** [ping/odmpy#56]
**Describe the problem**
A clear and concise description of what the bug/error is. If there is an error traceback dump, paste the text here (please avoid screenshots).

**To Reproduce**
Please include the full command used, for example `odmpy libby --direct`

**Version/Environment**
Please paste the contents of `odmpy --version` here.

**Comment by ping** [comment]
To use this tool, you don't need to know python, but you need to be comfortable installing and running programs with a [command line interface (CLI)](https://en.wikipedia.org/wiki/Command-line_interface). To start, you can refer to the [README](https://github.com/ping/odmpy#readme).

If you're not comfortable with the CLI, this tool is probably not suitable for you.

If all you want to do is to download audiobook loans from Libby, there are browser extensions that do that (please search for it) and may be simpler to use.

**Comment by ojmw** [comment]
> To use this tool, you don't need to know python, but you need to be comfortable installing and running programs with a [command line interface (CLI)](https://en.wikipedia.org/wiki/Command-line_interface). To start, you can refer to the [README](https://github.com/ping/odmpy#readme).
> 
> If you're not comfortable with the CLI, this tool is probably not suitable for you.
> 
> If all you want to do is to download audiobook loans from Libby, there are browser extensions that do that (please search for it) and may be simpler to use.

Thank you very much!
