### ISSUE TITLE
Long chapters are split into too-small chapters with duplicate names 

### ISSUE THREAD

**Issue by xavdid** [ping/odmpy#57]
**Describe the problem**

When adding chapter markers to a book with very long chapters, duplicate markers are added with the suffix `(00:00)`. 

Chapters In Libby:

![IMG_8273](https://github.com/ping/odmpy/assets/1231935/30536f7a-55de-46da-8e1c-6e5aa98d01b0)

Chapters after extraction:

![IMG_8272](https://github.com/ping/odmpy/assets/1231935/57d5b767-7d2b-4085-9bb8-e8eb2411358b)

The book otherwise plays great, so this is fairly minor in the scheme of things.

**To Reproduce**

I noticed it with [this version of Good Omens](https://nypl.overdrive.com/media/4712440), but I think I've seen it other places too.

I ran:

```
odmpy libby --settings ~/.config/odmpy --latest 1 --downloaddir ~/Downloads/audiobooks --chapters --merge --mergeformat m4b --nobookfolder --bookfileformat "%(Author)s - %(Series)s %(ReadingOrder)s - %(Title)s"
```

**Version/Environment**
 
```
odmpy 0.8.1 [Python 3.11.4-darwin]

ffmpeg version 6.0 Copyright (c) 2000-2023 the FFmpeg developers
  built with Apple clang version 14.0.3 (clang-1403.0.22.14.1)
```

**Comment by ping** [comment]
Add the `--direct` option to your command. This should get you the same chapters as the Libby interface.

**Comment by xavdid** [comment]
That looks to have fixed it, thank you!
