### ISSUE TITLE
403 error upon using odmlibby

### ISSUE THREAD

**Issue by nerdguy1338** [ping/odmpy#62]
Using odm libby now produces this

 odmpy libby
odmpy Interactive Client for Libby
----------------------------------------------------------------------
An unexpected error has occurred
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/odmpy/libby.py", line 357, in make_request
    res.raise_for_status()
  File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://sentry-read.svc.overdrive.com/chip/sync

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/odmpy/odm.py", line 846, in run
    synced_state = libby_client.sync()
  File "/usr/local/lib/python3.10/dist-packages/odmpy/libby.py", line 457, in sync
    res: Dict = self.make_request("chip/sync")  File "/usr/local/lib/python3.10/dist-packages/odmpy/libby.py", line 366, in make_request
    ErrorHandler.process(http_err)
  File "/usr/local/lib/python3.10/dist-packages/odmpy/libby_errors.py", line 103, in process    raise ClientError(
odmpy.libby_errors.ClientError: <odmpy.libby_errors.ClientError; http_status=403, msg='403 Client Error: Forbidden for url: https://sentry-read.svc.overdrive.com/chip/sync', error_response='{"result":"missing_chip"}''>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/odmpy/libby.py", line 357, in make_request
    res.raise_for_status()
  File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://sentry-read.svc.overdrive.com/chip/sync

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/odmpy", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/odmpy/__main__.py", line 27, in main
    run()
  File "/usr/local/lib/python3.10/dist-packages/odmpy/odm.py", line 846, in run
    synced_state = libby_client.sync()
  File "/usr/local/lib/python3.10/dist-packages/odmpy/libby.py", line 457, in sync
    res: Dict = self.make_request("chip/sync")  File "/usr/local/lib/python3.10/dist-packages/odmpy/libby.py", line 366, in make_request
    ErrorHandler.process(http_err)
  File "/usr/local/lib/python3.10/dist-packages/odmpy/libby_errors.py", line 103, in process    raise ClientError(
odmpy.libby_errors.ClientError: <odmpy.libby_errors.ClientError; http_status=403, msg='403 Client Error: Forbidden for url: https://sentry-read.svc.overdrive.com/chip/sync', error_response='{"result":"missing_chip"}''>

Installed following the install from source pip instructions, it was working perfectly 24 hours ago.

**Comment by adampalli** [comment]
I have the same issue :(

**Comment by cerinawithasea** [comment]
I do not remember if this was the error i got but i did get one. i just reset and it worked fine after. maybe that will help

**Comment by thisisandrewv** [comment]
having the same issue

**Comment by wtanksleyjr** [comment]
Could someone clarify what "reset" means? I'm trying to re-ID (copy all
cards from the website), and that doesn't work. What else could "reset"
imply?

-Wm

**Comment by ethan-y-guo** [comment]
Can confirm that using `odmpy libby --reset` and signing in again with a new code worked for me

More discussion here: https://www.mobileread.com/forums/showthread.php?p=4416158

**Comment by nerdguy1338** [comment]
Confirmed fix. Thank you, how did I miss the reset option? Haha.

Fantastic software, great job.

**Comment by wtanksleyjr** [comment]
Is there anything I'm missing? I ran `odmpy libby --reset`, then `odmpy
libby`, and then it asked me for the code (which I got from the libby web
app) -- but it returns an error,

`Could not log in with code. Make sure that you have entered the right code
and within the time limit.`

I've tried with a code from my phone's libby as well.

Should I be using a different command to be logging in? I hope???

-Wm

**Comment by nerdguy1338** [comment]
That sounds like a different problem. The reset and code method worked
perfectly for me.

**Comment by cerinawithasea** [comment]
sorry about that , reset is
  --reset               Remove previously saved odmpy Libby settings.
so i did odmpy libby --reset
then it will reset then go odmpy libby and it will ask for the copy code from the app

**Comment by wtanksleyjr** [comment]
Thanks guys, but it looks like this is a way bigger issue, it's absolutely
destroyed pylibby and odmpy. I can't do anything with either.

odmpy isn't throwing exceptions once I reset it, but pylibby is.

-Wm

**Comment by wtanksleyjr** [comment]
OK, finally got it.

1. apt update, upgrade, reboot, repeat.
2. only my phone's libby account can be copied; something about the website
resists me.

...and I'm up and running again. Dang.

-Wm
