### ISSUE TITLE
Can't figure out how to do this with windows.

### ISSUE THREAD

**Issue by Iceman253** [ping/odmpy#79]
Hi, you have the insallation instructions for macOS but there are no instructions for Windows, so I don't know what to do.

**Comment by coloradoruss** [comment]
I have odmpy on my windows computer on a virtual linux machine.
Probably not exactly what you were looking for, but that is what I have set
up.



Russ Breckenridge
Pink Realty Rentals
Property Management

Direct Contact:
(719) 630-1000 - Direct, Call only, Do not text
(303) 380-1000 - Direct, Call only, Do not text
(719) 629-7465 - Text message only
***@***.***

Office Contact:
(719) 393-7465 - Pink Realty, Main number
(719) 633-7000 - Property Management
(719) 260-6000 - Pink Realty Buyer Team
(719) 227-7000 - Pink Realty Seller Team
(719) 203-9000 - Transaction Coordinator
(800) 677-3253 - Fax

Check out our website for full access to all homes listed for sale in the
Pikes Peak, Denver, Pueblo, and Royal Gorge MLS systems.  www.PinkRealty.com
<http://www.pinkrealty.com/>

Check out our website for all of our currently available rental
properties.  www.PinkRentals.com



*Confidentiality Notice: This message may contain confidential and/or
privileged information.  If you are not the addressee or authorized to
receive this for the addressee, you must not use, copy, disclose, or take
any action based on this message or any information herein.  If you have
received this message in error, please advise the sender immediately by
reply e-mail and delete this message.Non-Binding and Expiration Disclaimer:
Content of emails, to include any included links and attachments thereto,
sent or received shall not create a binding contract or be construed to be
conveyance or acceptance of any offer, contract or any other agreement,
whatsoever, nor shall the same be binding on any party until a written
contract is signed by all parties.  In the event a bona fide, signed offer
is conveyed via email, the same shall expire, if not accepted and fully
executed by all parties, upon the latter of its explicitly stated
expiration date or, if such a date is not specified, twenty-four hours from
its initial transmission by the offeror and shall thereafter not be binding
on any party.*




*Wire Fraud Notice: Never trust wiring instructions sent via email. Cyber
criminals are hacking email accounts and sending emails with fake wiring
instructions. These emails are convincing and sophisticated. Always
independently confirm wiring instructions in person or via a telephone call
to a trusted and verified phone number. Never wire money without
double-checking that the wiring instructions are correct.Affiliated
Business Disclosure: I have an ownership interest in both Pink Realty, Inc
and Pink Realty Rentals and work closely with both companies and their
agents and employees, my real estate license and my brokerage activity is
with Pink Realty Rentals.*

**Comment by wtanksleyjr** [comment]
I think it works on Windows ... Did you try running the `python -m pip install ...` line given in the main page? Of course you have to install Python first, do you know how to do that?

**Comment by Iceman253** [comment]
Yes, I have python 3.12 installed and have run that in the command line. 
I may be using the wrong command to initiate odmpy, I just tried 'odmpy' and 'odmpy libby'

**Comment by Iceman253** [comment]
I am in C:/Users/<username> directory, do I have to cd to somewhere else?

**Comment by wtanksleyjr** [comment]
Pip is supposed to warn you if you install a script that is marked executable. Did you get a warning that looks loosely like the following:
```
  WARNING: The script f2py.exe is installed in 'C:\Users\atomi\AppData\Local\Programs\Python\Python310\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed numpy-1.23.5
```
If you can't remember, you can `pip uninstall` and `pip install` odmpy to see the warning again (if any). Once you get it, you'll need to add that directory to your PATH. (Doing that is another question, I'll be glad to help once you respond.)

**Comment by Iceman253** [comment]
Yes I did. But I just figured something out, I took a look at that warning and went to the source it was giving me. 'C:\Users\<user>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\Scripts'
there I tried the command and it worked, except now I'm not quite sure how to get a code because libby wants the device you're joining from to display a code so you can input it and doesn't give you a code to type in.
Otherwise, it needs you to use your passkey, and signing in with sonos speakers or or android automotive doesn't seem to work.

**Comment by CodeKid2024** [comment]
Otherwise, it needs you to use your passkey

**Comment by CodeKid2024** [comment]
shoud I try sign in with sonos speakers or something like that?

**Comment by wtanksleyjr** [comment]
Excellent! Yes, use either one of the alternatives, Sonos speakers or
Android Car.

HOWEVER, if you're using the version on ping/odmpy it won't work; a recent
change broke it again, and you'll want to install the fixed version instead.

So try running `python3 -m pip install git+
***@***.***/jordkh/odmpy.git --force-reinstall` before you
continue.

Sorry, ping hadn't been updating his repo, but this has the latest
certificate fix.

-Wm

**Comment by Iceman253** [comment]
Okay, thanks! Last question. Does this work with audiobooks and if so how should I download them.

**Comment by wtanksleyjr** [comment]
Yes and no. Yes, this is the best way to download audiobooks. No, it doesn't work perfectly, ever since Libby changed the site's security. Here's how to make it work:

1. As you've done, install. Feel free to log odmpy into Libby like you're doing, although its use will be limited (I use it to check that I've downloaded my checkedout books, and to get metadata).
2. For each book you check out, you have to get an ODM file from your library's site on overdrive.com; use [Overdrive's Find a Library page](https://www.overdrive.com/libraries) to look up your specific libraries. This step used to be handled by odmpy automatically, and hopefully we'll someday figure it out again. Anyhow, log into your library's Overdrive page using your card# and your pin (usually that's the last-4 of your phone number, although some libraries do that differently). Then go to your Loans page, click the "Have Overdrive" link on one of your loans, and you'll see a Download button. Click it and you'll get that ODM file downloaded.
3. NOW you can run `odmpy dl <ODMfile.odm>` and it'll get all the audio for your book in mp3 format.

Make sense? That middle step went on a bit long, let me know if you want a different breakdown. It's pretty easy once you get used to it. Oh, Libby and Overdrive are the same system, everything checked out on one is automatically checked out on the other.

**Comment by Iceman253** [comment]
Thank you so much! That worked! The only weird thing is that the parts don't necessarily reflect the chapters.

**Comment by wtanksleyjr** [comment]
Fantastic. One more tip: all of odmpy's libby stuff is optional. If it breaks or if you don't wind up using it, just download the ODM and run "odmpy dl <ODMfile>". I personally like having it as a list of what I've checked out, but it's up to you.

**Comment by wtanksleyjr** [comment]
Oh, yes, the chaptering is hidden inside the MP3 files - there are options in odmpy to rebuild the mp3s into chapters, but I don't know how to use them. Bookreaders like "Listen" and "Audiobookshelf" (which is what I use) automatically read the hidden chapter information as-is.

**Comment by birlorg** [comment]
@wtanksleyjr did a great job with instructions on how to use it now.

This is what I do for the download bit:

`odmpy dl <file> -m --mergeformat m4b --mergecodec aac`

Which will merge all the individual mp3 files into a single file, making it easier to manage.
