### ISSUE TITLE
Downloading Audiobooks Broken up by Chapter Markers

### ISSUE THREAD

**Issue by Iceman253** [ping/odmpy#80]
Hi, I just was wondering if it as possible to use odmpy to download the chapters of an audiobook instead of the "parts" and and then preferably name them. Doesn't really matter, but would be helpful.

**Comment by wtanksleyjr** [comment]
The closest odmpy comes to that is that it'll combine all of the files into an m4b file tagged with the chapters (it's the most common standard for audiobooks). Given that, other programs can easily split chapters into separate m4b files (almost instantly). Someone posted the command line to have odmpy do that combining into our previous discussion, I don't use it myself so I don't remember.

**Comment by coloradoruss** [comment]
odmpy dl -cmjk -mergeformat m4b



Russ Breckenridge
Pink Realty Rentals
Property Management

Direct Contact:
(719) 630-1000 - Direct, Call only, Do not text
(303) 380-1000 - Direct, Call only, Do not text
(719) 629-7465 - Text message only
***@***.***

Office Contact:
(719) 393-7465 - Pink Realty, Main number
(719) 633-7000 - Property Management
(719) 260-6000 - Pink Realty Buyer Team
(719) 227-7000 - Pink Realty Seller Team
(719) 203-9000 - Transaction Coordinator
(800) 677-3253 - Fax

Check out our website for full access to all homes listed for sale in the
Pikes Peak, Denver, Pueblo, and Royal Gorge MLS systems.  www.PinkRealty.com
<http://www.pinkrealty.com/>

Check out our website for all of our currently available rental
properties.  www.PinkRentals.com



*Confidentiality Notice: This message may contain confidential and/or
privileged information.  If you are not the addressee or authorized to
receive this for the addressee, you must not use, copy, disclose, or take
any action based on this message or any information herein.  If you have
received this message in error, please advise the sender immediately by
reply e-mail and delete this message.Non-Binding and Expiration Disclaimer:
Content of emails, to include any included links and attachments thereto,
sent or received shall not create a binding contract or be construed to be
conveyance or acceptance of any offer, contract or any other agreement,
whatsoever, nor shall the same be binding on any party until a written
contract is signed by all parties.  In the event a bona fide, signed offer
is conveyed via email, the same shall expire, if not accepted and fully
executed by all parties, upon the latter of its explicitly stated
expiration date or, if such a date is not specified, twenty-four hours from
its initial transmission by the offeror and shall thereafter not be binding
on any party.*




*Wire Fraud Notice: Never trust wiring instructions sent via email. Cyber
criminals are hacking email accounts and sending emails with fake wiring
instructions. These emails are convincing and sophisticated. Always
independently confirm wiring instructions in person or via a telephone call
to a trusted and verified phone number. Never wire money without
double-checking that the wiring instructions are correct.Affiliated
Business Disclosure: I have an ownership interest in both Pink Realty, Inc
and Pink Realty Rentals and work closely with both companies and their
agents and employees, my real estate license and my brokerage activity is
with Pink Realty Rentals.*
