### ISSUE TITLE
Can no longer download odm files

### ISSUE THREAD

**Issue by Iceman253** [ping/odmpy#82]
**Describe the problem**
overdrive pulled their support for odm files now that the overdrive app is no longer active.

![image](https://github.com/user-attachments/assets/6971d8a3-6571-4c01-9ae5-427a6545b629)

**Comment by 2600box** [comment]
Use this bookmarklet to download the odm files: https://gist.github.com/ping/b58ae66359691db1d08f929a9e57a03d

Then use this fork to download the audiobooks: https://github.com/jordkh/odmpy

**Comment by CodeKid2024** [comment]
I'm sorry, I don't know Javascript. I program in python and C#. Could you explain that one to me and how to use it?

**Comment by CodeKid2024** [comment]
I already have the correct fork though.

**Comment by CodeKid2024** [comment]
I do not have the overdrive app, I never needed it because of odmpy.

**Comment by CodeKid2024** [comment]
I just copied and basted the bookmarklet, put it in my bookmark bar, and then ran it in the libby audiobook link but it simply made the libby window go black.

**Comment by Iceman253** [comment]
Hey thanks! That worked perfectly!

**Comment by 2600box** [comment]
The instructions on how to create and use the bookmarklet are there at the top. If any of the steps are not clear, I can try to clarify further, just let me know where you are stuck?

/* 1. Paste this entire gist over at https://mrcoles.com/bookmarklet/ to generate a bookmarklet */
/* 2. Use a meaningful Name like: 🎧 📖 Links */
/* 3. Drag the generated bookmarklet link to your Bookmarks Toolbar. */
/* 4. Click on the bookmarklet when you're on the Overdrive loan page, e.g. https://yourlibrary.overdrive.com/account/loans */
/* 5. The "Download MP3 audiobook" link should appear like it used to. */

**Comment by Iceman253** [comment]
Sorry, I was confused until I realized it was meant to be used on the loans page.

**Comment by Iceman253** [comment]
I deleted my previous comments after that.
